import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/page";
import { Providers } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
  try {
    // remove any attributes added by browser extensions that start with data-smart-converter
    const removeAttrs = (el) => {
      if (!el || !el.getAttributeNames) return;
      for (const name of el.getAttributeNames()) {
        if (name && name.startsWith('data-smart-converter')) {
          el.removeAttribute(name);
        }
      }
    };
    removeAttrs(document.documentElement);
    removeAttrs(document.body);
    // also walk immediate children of body (fast, not deep) to be safe
    if (document.body && document.body.children) {
      for (const c of Array.from(document.body.children)) removeAttrs(c);
    }
  } catch (e) { /* ignore */ }
})();`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <div className="container mx-auto py-5">
            {children}
            <Toaster />
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
